# Insert product
POST http://localhost:4002/products
content-type: application/json

{
  "name": "Name",
  "price": 0
}

###
# Get all products
GET http://localhost:4002/products


###
# Get products by id
GET http://localhost:4002/products/id

###
# Update product
PUT http://localhost:4002/products/id
content-type: application/json

{
  "name": "Name",
  "price": 0
}

###
# Delete product
DELETE http://localhost:4002/products/id